secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  airflow_db_password:
    file: ./secrets/airflow_db_password.txt
  warehouse_password:
    file: ./secrets/warehouse_password.txt

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  secrets:
    - airflow_db_password
    - postgres_password
    - warehouse_password
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_CMD=bash -c "echo -n postgresql+psycopg2://airflow_user:$(cat /run/secrets/airflow_db_password)@metadata_db/airflow_metadata"
    - AIRFLOW_CONN_POSTGRES_WAREHOUSE=postgresql://warehouse_admin:warehouse_pass@warehouse_db:5432/data_warehouse
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  volumes:
    - ./orchestration/dags:/opt/airflow/dags
    - ./src:/opt/airflow/src
    - ./data:/opt/airflow/data
    - ./jars:/opt/airflow/jars
    - ./logs:/opt/airflow/logs
    - ./models:/opt/airflow/models
    - ./secrets:/opt/airflow/secrets
  depends_on:
    metadata_db:
      condition: service_healthy
  networks:
    - data-pipeline-net

services:

  metadata_db:
    image: postgres:15
    container_name: pizza_metadata_db
    restart: always
    secrets:
      - postgres_password
      - airflow_db_password
    environment:
      POSTGRES_USER: root_admin
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - metadata_data:/var/lib/postgresql/data
      - ./init_metadata.sql:/docker-entrypoint-initdb.d/init_metadata.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root_admin"]
      interval: 10s
      retries: 5
    networks:
      - data-pipeline-net

  warehouse_db:
    image: postgres:15
    container_name: pizza_warehouse_db
    restart: always
    secrets:
      - warehouse_password
    environment:
      POSTGRES_USER: warehouse_admin
      POSTGRES_PASSWORD_FILE: /run/secrets/warehouse_password
      POSTGRES_DB: data_warehouse
    ports:
      - "5433:5432"
    volumes:
      - warehouse_data:/var/lib/postgresql/data
      - ./init_warehouse.sql:/docker-entrypoint-initdb.d/init_warehouse.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "warehouse_admin", "-d", "data_warehouse"]
      interval: 10s
      retries: 5
    networks:
      - data-pipeline-net

  airflow-init:
    <<: *airflow-common
    container_name: pizza_airflow_init
    command: bash -c "airflow db migrate && airflow users create --username admin --password $(cat /run/secrets/postgres_password) --firstname Pizza --lastname Admin --role Admin --email admin@pizza.com"

  airflow-webserver:
    <<: *airflow-common
    container_name: pizza_airflow_webserver
    command: airflow webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: pizza_airflow_scheduler
    command: airflow scheduler
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  metabase:
    image: metabase/metabase:latest
    container_name: pizza_metabase
    restart: always
    ports:
      - "3000:3000"
    secrets:
      - postgres_password
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_app_db
      MB_DB_PORT: 5432
      MB_DB_USER: root_admin
      MB_DB_PASS_FILE: /run/secrets/postgres_password
      MB_DB_HOST: metadata_db
    networks:
      - data-pipeline-net
    depends_on:
      metadata_db:
        condition: service_healthy
      warehouse_db:
        condition: service_healthy

volumes:
  metadata_data:
  warehouse_data:

networks:
  data-pipeline-net:
    driver: bridge